namespace TwT.Rdw.Models.API
{
    internal class VehicleInformationModel
    {
        public string kenteken { get; set; }
        public string voertuigsoort { get; set; }
        public string merk { get; set; }
        public string handelsbenaming { get; set; }
        public decimal vervaldatum_apk { get; set; }
        public decimal datum_tenaamstelling { get; set; }
        public decimal bruto_bpm { get; set; }
        public string inrichting { get; set; }
        public decimal aantal_zitplaatsen { get; set; }
        public string eerste_kleur { get; set; }
        public string tweede_kleur { get; set; }
        public decimal aantal_cilinders { get; set; }
        public decimal cilinderinhoud { get; set; }
        public decimal massa_ledig_voertuig { get; set; }
        public decimal toegestane_maximum_massa_voertuig { get; set; }
        public decimal massa_rijklaar { get; set; }
        public decimal maximum_massa_trekken_ongeremd { get; set; }
        public decimal maximum_trekken_massa_geremd { get; set; }
        public decimal datum_eerste_toelating { get; set; }
        public decimal datum_eerste_tenaamstelling_in_nederland { get; set; }
        public string wacht_op_keuren { get; set; }
        public decimal catalogusprijs { get; set; }
        public string wam_verzekerd { get; set; }
        public decimal maximale_constructiesnelheid { get; set; }
        public decimal laadvermogen { get; set; }
        public decimal oplegger_geremd { get; set; }
        public decimal aanhangwagen_autonoom_geremd { get; set; }
        public decimal aanhangwagen_middenas_geremd { get; set; }
        public decimal aantal_staanplaatsen { get; set; }
        public decimal aantal_deuren { get; set; }
        public decimal aantal_wielen { get; set; }
        public decimal afstand_hart_koppeling_tot_achterzijde_voertuig { get; set; }
        public decimal afstand_voorzijde_voertuig_tot_hart_koppeling { get; set; }
        public decimal afwijkende_maximum_snelheid { get; set; }
        public decimal lengte { get; set; }
        public decimal breedte { get; set; }
        public string europese_voertuigcategorie { get; set; }
        public string europese_voertuigcategorie_toevoeging { get; set; }
        public string europese_uitvoeringcategorie_toevoeging { get; set; }
        public string plaats_chassisnummer { get; set; }
        public decimal technische_max_massa_voertuig { get; set; }
        public string type { get; set; }
        public string type_gasinstallatie { get; set; }
        public string variant { get; set; }
        public string uitvoering { get; set; }
        public decimal volgnummer_wijziging_eu_typegoedkeuring { get; set; }
        public decimal vermogen_massarijklaar { get; set; }
        public decimal wielbasis { get; set; }
        public string export_indicator { get; set; }
        public string openstaande_terugroepactie_indicator { get; set; }
        public decimal vervaldatum_tachograaf { get; set; }
        public string taxi_indicator { get; set; }
        public decimal maximum_massa_samenstelling { get; set; }
        public decimal aantal_rolstoelplaatsen { get; set; }
        public decimal maximum_ondersteunende_snelheid { get; set; }
        public decimal jaar_laatste_registratie_tellerstand { get; set; }
        public string tellerstandoordeel { get; set; }
        public string code_toelichting_tellerstandoordeel { get; set; }
        public string tenaamstellen_mogelijk { get; set; }
        public DateTime vervaldatum_apk_dt { get; set; }
        public DateTime datum_tenaamstelling_dt { get; set; }
        public DateTime datum_eerste_toelating_dt { get; set; }
        public DateTime datum_eerste_tenaamstelling_in_nederland_dt { get; set; }
        public DateTime vervaldatum_tachograaf_dt { get; set; }
        public decimal maximum_last_onder_de_vooras_sen_tezamen_koppeling { get; set; }
        public string type_remsysteem_voertuig_code { get; set; }
        public string rupsonderstelconfiguratiecode { get; set; }
        public decimal wielbasis_voertuig_minimum { get; set; }
        public decimal wielbasis_voertuig_maximum { get; set; }
        public decimal lengte_voertuig_minimum { get; set; }
        public decimal lengte_voertuig_maximum { get; set; }
        public decimal breedte_voertuig_minimum { get; set; }
        public decimal breedte_voertuig_maximum { get; set; }
        public decimal hoogte_voertuig { get; set; }
        public decimal hoogte_voertuig_minimum { get; set; }
        public decimal hoogte_voertuig_maximum { get; set; }
        public decimal massa_bedrijfsklaar_minimaal { get; set; }
        public decimal massa_bedrijfsklaar_maximaal { get; set; }
        public decimal technisch_toelaatbaar_massa_koppelpunt { get; set; }
        public decimal maximum_massa_technisch_minimaal { get; set; }
        public decimal maximum_massa_technisch_maximaal { get; set; }
        public string subcategorie_nederland { get; set; }
        public string verticale_belasting_koppelpunt_getrokken_voertuig { get; set; }
        public string zuinigheidsclassificatie { get; set; }
        public string registratie_datum_goedkeuring_afschrijvingsmoment_bpm { get; set; }
        public DateTime registratie_datum_goedkeuring_afschrijvingsmoment_bpm_dt { get; set; }
    }
}